### ISSUE TITLE
Multiplication symbol typo

### ISSUE THREAD

**Issue by aanastasiou** [cerus/edina#1]
### Issue description

Typo in README.md

### To reproduce

Navigate to the project's github repository and read section "Specification"

### Expected behaviour

`*  # Pop top two items and push product`

### Screenshots / videos

![image](https://user-images.githubusercontent.com/1336337/184476733-7d88e272-8530-4385-860e-5f1d0054a866.png)

### Component

Docs

### Additional information

...sorry to be the typo person. Cool project anyway.

**Comment by cerus** [comment]
Thank you for the bug report! I really appreciate that you took the time to read the README and report the issue. I'll fix it, thanks :)

**Comment by cerus** [comment]
Fixed in 160f711dc6177fcd084444b0c43407d1f2dd343f. I've noticed a few other issues and missing specs that I've fixed as well. Thanks again!
